# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\digitcorp\crm\module\:
        resource: '../src/digitcorp/crm/module/*'
        exclude: '../src/digitcorp/crm/module/{entreprise, user, task, security, dashboard, project}/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\digitcorp\crm\module\dashboard\Controller\:
        resource: '../src/digitcorp/crm/module/dashboard/Controller'
        tags: ['controller.service_arguments']
    App\digitcorp\crm\module\entreprise\Controller\:
        resource: '../src/digitcorp/crm/module/entreprise/Controller'
        tags: ['controller.service_arguments']
    App\digitcorp\crm\module\project\Controller\:
        resource: '../src/digitcorp/crm/module/project/Controller'
        tags: ['controller.service_arguments']
    App\digitcorp\crm\module\task\Controller\:
        resource: '../src/digitcorp/crm/module/task/Controller'
        tags: ['controller.service_arguments']
    App\digitcorp\crm\module\user\Controller\:
        resource: '../src/digitcorp/crm/module/user/Controller'
        tags: ['controller.service_arguments']
    App\digitcorp\crm\module\security\Controller\:
        resource: '../src/digitcorp/crm/module/security/Controller'
        tags: ['controller.service_arguments']